# Generated by Django 3.0.3 on 2020-12-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctoral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=50)),
                ('programme', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=1000)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Postgraduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=50)),
                ('programme', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=1000)),
                ('department', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Undergraduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=50)),
                ('programme', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=1000)),
                ('department', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=50)),
            ],
        ),
    ]
