# Generated by Django 3.0.3 on 2021-01-09 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20210109_2358'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgraduate',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering Department'), ('ECE', 'Electronics and Communication Department'), ('MCS', 'Mathematics and Computation Department')], max_length=50),
        ),
        migrations.AlterField(
            model_name='postgraduate',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Faculty'),
        ),
        migrations.AlterField(
            model_name='postgraduate',
            name='programme',
            field=models.CharField(choices=[('M.Tech. CSE', 'M.Tech. Computer Science'), ('M.Tech. CSIS', 'M.Tech. Computer Science (Information Security)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='postgraduate',
            name='semester',
            field=models.CharField(choices=[('I', 'First'), ('II', 'Second'), ('III', 'Third'), ('IV', 'Fourth')], max_length=20),
        ),
        migrations.AlterField(
            model_name='undergraduate',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering Department'), ('ECE', 'Electronics and Communication Department'), ('MCS', 'Mathematics and Computation Department')], max_length=50),
        ),
        migrations.AlterField(
            model_name='undergraduate',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Faculty'),
        ),
        migrations.AlterField(
            model_name='undergraduate',
            name='programme',
            field=models.CharField(choices=[('B.Tech. CSE', 'B.Tech. Computer Science and Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='undergraduate',
            name='semester',
            field=models.CharField(choices=[('I', 'First'), ('II', 'Second'), ('III', 'Third'), ('IV', 'Fourth'), ('V', 'Fifth'), ('VI', 'Sixth'), ('VII', 'Seventh'), ('VIII', 'Eighth')], max_length=20),
        ),
    ]
