# Generated by Django 3.0.3 on 2021-01-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210110_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoral',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering Department'), ('ECE', 'Electronics and Communication Department'), ('MCS', 'Mathematics and Computation Department')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doctoral',
            name='programme',
            field=models.CharField(choices=[('Ph. D', 'Ph. D.')], max_length=50),
        ),
    ]
