# Generated by Django 3.0.3 on 2021-01-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20210109_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstaff',
            name='area_of_interest',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectstaff',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Faculty'),
        ),
    ]
